export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',

    SIGNUP_REQUEST : 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS : 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE : 'SIGNUP_FAILURE',
    
    SEND_EMAIL_REQUEST : 'SEND_EMAIL_REQUEST',
    SEND_EMAIL_SUCCESS : 'SEND_EMAIL_SUCCESS',
    SEND_EMAIL_FAILURE : 'SEND_EMAIL_FAILURE',
}
